name: mention-to-slack-actions

on:
  [issues, issue_comment, pull_request, pull_request_review, pull_request_review_comment]

jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Mention to Slack Actions
        uses: Laurenfrost/mention-to-slack@latest
        with:
          configuration-path: .github/mention-to-slack.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          icon-url: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          bot-name: ${{github.repository}}
          run-id: ${{ github.run_id }}
          debug-flag: true
